import { ThemeProvider } from "@/contexts/ThemeProvider";
import "@/styles/globals.css";
import CustomCursor from "@/components/CustomCursor";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactLenis from "lenis/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactLenis root>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CustomCursor />
            {children}
          </ThemeProvider>
        </ReactLenis>
      </body>
    </html>
  );
}
